# Generated by Django 4.1 on 2023-04-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('Intial_Datetime', models.DateTimeField()),
                ('timezone', models.IntegerField()),
                ('Embrace_firmware_version', models.CharField(max_length=20)),
                ('App', models.CharField(max_length=10)),
                ('App_version', models.CharField(max_length=10)),
                ('Mobile_OS', models.CharField(max_length=10)),
                ('Mobile_OS_version', models.CharField(max_length=10)),
                ('GTCS_algortithm_version', models.CharField(max_length=10)),
                ('sensor_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('timezone', models.IntegerField()),
                ('UNIX_timestamp', models.FloatField()),
                ('Acc_magnitude_avg', models.FloatField()),
                ('eda_avg', models.FloatField()),
                ('Temp_avg', models.FloatField()),
                ('movement_intensity', models.IntegerField()),
                ('Steps', models.IntegerField()),
                ('rest', models.IntegerField()),
                ('on_wrist', models.BooleanField()),
                ('sensor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.sensor', verbose_name='Sensors')),
            ],
            options={
                'verbose_name_plural': 'SesnorData',
            },
        ),
    ]
