# Generated by Django 4.1 on 2023-04-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sensor_timezone_remove_sensordata_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='Intial_Datetime',
            new_name='UTC_Datetime',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='datetime',
            new_name='UTC_Datetime',
        ),
        migrations.AddField(
            model_name='sensor',
            name='timezone_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timezone_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
