# Generated by Django 4.1 on 2023-04-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_intial_datetime_sensor_utc_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='timezone_datetime',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='timezone_datetime',
        ),
    ]
