# Generated by Django 4.1 on 2023-04-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sensor_timezone_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
    ]
