# Generated by Django 4.1 on 2023-04-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sensor_timezone_offset_sensordata_timezone_offset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['sensor_id', 'UTC_Datetime'], 'verbose_name_plural': 'SesnorData'},
        ),
    ]
